### ISSUE TITLE
How can I embed my native engine?

### ISSUE THREAD

**Issue by amerkoleci** [cocos-creator/editor-framework#218]
Hi guys,
Excellent work on this project, I have my engine written in C++ with support for DirectX11, DirectX12, Vulkan etc, how can I integrate my engine here?
How would i be able to render my native stuff into the web parts? 
What about communication?

Thank you

**Comment by jwu** [comment]
Currently editor-framework only support WebGL rendering. My advice is write a webGL renderer support basic rendering of your scene data for editing, and when you start running, spawn a process which will load the scene you are editing with your native renderer.

**Comment by jwu** [comment]
The electron team recently expose an interface for user to create a browser-window with native window handle: https://github.com/atom/electron/blob/master/docs/api/browser-window.md#wingetnativewindowhandle, with this interface, it could be possible render your stuff with your native renderer. But we haven't dived too much on this approach.

**Comment by amerkoleci** [comment]
What do you mean by:
Create webGL renderer support basic rendering of your scene data for editing, and when you start running, spawn a process which will load the scene you are editing with your native renderer.

**Comment by jwu** [comment]
I mean you need to write a javascript renderer which use webGL so that it can be show in Editor Framework's window, and that can help you edit 3D scene with basic rendering support. 

When you finish editing your scene, and want to render it by advanced effect, you can click a button in the editor, and spawn a process which will start your cpp renderer, and this renderer will load the 3D data you are editing in your Editor-Framework app.
