### ISSUE TITLE
Cleaner, simpler and faster tests by using mocha/chai?

### ISSUE THREAD

**Issue by Aerlinger** [cocos-creator/editor-framework#327]
It seems as though there's currently an excessive amount of configuration and setup for testing. Much of the existing code to support testing is also tangled in the production code (particularly in`lib/tester` and also much arg/condition testing in the root `index.js`). 

It seems that testing in Electron is significantly more mature than it was a year ago. Perhaps much of the present testing complexity could be mitigated by refactoring and consolidating the test code by using a single test framework, such as mocha, in lieu of the hybrid tap/mocha implementation currently in place. 

Additionally, there have been several recent projects to facilitate unit and integration testing in Electron worth exploring:
   - Electron mocha: https://github.com/jprichardson/electron-mocha
   - Spectron: https://github.com/electron/spectron

The integration tests will certainly be more difficult to refactor, but happy to help in this regard if it would be helpful.

**Comment by jwu** [comment]
Hi Aerlinger,

Actually editor-framework shift to node-tap recently from Mocha+Chai+Sinon, and the reason for it is to make the test code simple and clean.

We've already evaluated electron-mocha and spectron, those are good solution for simple Electron apps. But they eventually failed in some how for some of my cases, such as: 

  - testing IPC from multiple window
  - testing code send and reply between main and renderer process
  - preload library code seamless
  - sending test result through back to main process
  - and so on ...

That's why we decide to develop our own one.

BTW: We only use node-tap for testing, where does the "hybrid tap/mocha" come from?

My question is: Which step for testing in editor-framework make you feel the test s complex? May be I can optimize it.

**Comment by Aerlinger** [comment]
It's just the initialization process and steps necessary for bootstrapping the test framework that seem a little complex. 

Here's my understanding of the process:

1. Execute `tasks/run-tests.js` task 
2. spawn child electron test process via `test/package.json` with valid test args 
3. execute `test/runner.js` to load base editor-framework root via `./index.js`
4. Within index.js parse args and run `tester/index.js` to load test helpers and utilities
5. Within `tester/index.js` parse additional args and iterate through each test example in `test/**/*`, injecting relevant fixtures and test code and store the result of each test.

However, the individual tests themselves are pretty easy to read and manage.  

I only brought this up partially out of curiosity, but also because I noticed that some very large and successful projects like N1 were using Spectron and Mocha for testing, including for some of the issues you've mentioned. And also because the existing Editor-Framework tests use a BDD format similar to that of Mocha/Jasmine.

Anyhow, I completely understand that managing tests isn't trivial especially in Electron, so if the current system works well, then it doesn't make sense to make any changes.

**Comment by jwu** [comment]
OK, I think the `unit-test.md` (which I've deleted just now) may mis-leading the way. Anyway, here is the detail:

There are three parts of tests in Editor-Framework:

  1. Editor Framework itself
  2. App (who use Editor-Framework to build their app)
  3. Packages

For the first part, the `README.md` already explains it.

For the 2nd part, it is similar to Editor-Framework's tests, so `README.md` still works for it. *BUT*, since you are writing your own App, booting the tests actually means minimal boots your App, so you are in charge of which modules you wish to load before running the tests.

Finally the 3rd part is missing currently. The way it works is, put your tests in `test` folder in your package. and the test files should be lived in `test/main` or `test/renderer` folders. Here is an example for it: https://github.com/fireball-packages/tester/tree/master/test

Let's review your step:

> 1. Execute `tasks/run-tests.js` task 
this is for running all the tests for 1st and 2nd part

> 2. spawn child electron test process via `test/package.json` with valid test args 
deprecated

> 3. execute `test/runner.js` to load base editor-framework root via `./index.js`
Not exactly, this is done automatically indeed, as long as you put the code `Tester.run` in your App. This is what Editor-Framework wishes their users to do with their Apps. Before `Tester.run`, user should take care of the init codes for their Apps for testing.

> 4. Within index.js parse args and run `tester/index.js` to load test helpers and utilities
Same as 3

> 5. Within `tester/index.js` parse additional args and iterate through each test example in `test/**/*`, injecting relevant fixtures and test code and store the result of each test.
Same as 3

To dive deeper, let's think about when you finish your app, and try to test it. You probably run it as `Foobar test -- [my] [test] [options]` (suppose Foobar is your app name), no matter how you initialize your app, finally it will go to `Tester.run` to start the tests Editor-Framework gives you, and that is why the test framework design like this --- it gives users the ability to customize their initialize codes before tests running in both main and renderer process.
