### ISSUE TITLE
Are Polymer panels/elements actually deprecated?

### ISSUE THREAD

**Issue by Aerlinger** [cocos-creator/editor-framework#353]
This is noted in the docs here: https://github.com/cocos-creator/editor-framework/tree/master/docs.

However, there are still many references to polymer panels/elements in the code, documentation, and examples with no indication of deprecation. Just wanted clarification on this.

**Comment by jwu** [comment]
It is deprecated. The legacy code (most are examples, I'm sure there is no Polymer code in Editor-Framework except some utility function) will be removed slowly. 

Editor-Framework recommend user choose their UI framework in their own. But if there must be one, Vue is currently the first choice since Editor-Framework's internal ui-kit work quite well with it.

Unlike legacy code, I will still leave the document relate with Polymer, but they will put to 'Working with 3rd ui-framework' category with Vue and others.
