### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by waywardmonkeys** [cocos-creator/editor-framework#42]
Where would someone modify to add TypeScript package support?

**Comment by jwu** [comment]
You can fork and add typescript compile code here: https://github.com/fireball-x/editor-framework/blob/master/core/build-package.js 

currently i found two gulp plugin to do typescript compile:

 - https://github.com/ivogabe/gulp-typescript
 - https://github.com/kotas/gulp-tsc

don't forget to add it to dependencies in package.json. Let me known if you have any issue in doing this :)

**Comment by waywardmonkeys** [comment]
You can skip some of the build process entirely if you use something like https://github.com/paulcbetts/electron-compile

That seems like it might be a big simplification.

**Comment by jwu** [comment]
Thanks for your information, the electron-compile looks great! 

I have two question about this solution:

1. Does that means the cache files will grow up unlimited?
2. What is the cache checking method used in it? sha for the content? will this slow down the loading time when checking if a file needs to compile?

So far, I can't use it because some reasons: 

1. electron-compile hooks the file/http protocol, in editor-framework and project relate with it (fireball), I have several additional protocol, such as `editor-framework://`, `app://` and `packages://`, and I do not known what kind of protocol user may added.

2. it seems that it is difficult for electron-compile to control the compile things, especially the js type. It can not known if the js should use Babel or not. The only way it does is turn on/off the babel entirely.

3. My compile solution including large file process such as pictures or sound (since the editor-framework is designed for fireball at first, and it needs to take care about game resources), so if the cache increase without limitation, the disk space will gone fast.

Again, many thanks in your advice, I think I will give it a try in some how.

**Comment by waywardmonkeys** [comment]
> Does that means the cache files will grow up unlimited?

I don't know!

> What is the cache checking method used in it? sha for the content? will this slow down the loading time when checking if a file needs to compile?

Again, I don't know yet.

> electron-compile hooks the file/http protocol, in editor-framework and project relate with it (fireball), I have several additional protocol, such as editor-framework://, app:// and packages://, and I do not known what kind of protocol user may added.

This seems like something that can be solved though, perhaps with a patch to the upstream.

> it seems that it is difficult for electron-compile to control the compile things, especially the js type. It can not known if the js should use Babel or not. The only way it does is turn on/off the babel entirely.

There's a mechanism for disabling Babel on JS files.

As the README says:

    Add ``'use nobabel'``; to the top of your file to opt-out of Babel compilation.

> My compile solution including large file process such as pictures or sound (since the editor-framework is designed for fireball at first, and it needs to take care about game resources), so if the cache increase without limitation, the disk space will gone fast.

Well, in this case, you don't need to copy everything from one directory to another. You just run from the plugin's package directory and ``electron-compile`` would handle intercepting and dealing with the loading of script and style files.

**Comment by waywardmonkeys** [comment]
I opened some bugs on the ``electron-compile`` repo about these issues.

**Comment by jwu** [comment]
I saw that, thanks man :+1:
